# Generated by Django 3.2.3 on 2021-06-25 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workpackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('procedure', models.CharField(blank=True, default='', max_length=255)),
                ('date_of_creation', models.DateField(auto_now_add=True)),
                ('planned_start_date', models.DateField(blank=True, null=True)),
                ('planned_end_date', models.DateField(blank=True, null=True)),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('planned_efforts', models.IntegerField(null=True)),
                ('actual_efforts', models.IntegerField(null=True)),
                ('project_lead_column', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='lead_column', to='main.column')),
                ('project_team_column', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_column', to='main.column')),
            ],
            options={
                'order_with_respect_to': 'project_lead_column',
            },
        ),
    ]
