# Generated by Django 3.2.3 on 2021-06-27 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_uploadeddocuments'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocuments',
            name='workpackage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='main.workpackage'),
            preserve_default=False,
        ),
    ]
